### PR TITLE
Test UMA process on Sepolia

### PR DESCRIPTION
**Pull request by ThimSouza**

### CODE REVIEW

**Review by claudiovb — COMMENTED** [review]
Partial review

**Review by claudiovb — CHANGES_REQUESTED** [review]
None of the tests works

**Comment by Potolski** [comment]
> None of the tests works

This is most likely a problem with the submodules/remappings

**Comment by ThimSouza** [comment]
The problem with tests failing was about EVM version config on foundry. Suggested by @Potolski to use Cancun as EVM, now tests running

**Pull request merged**
